### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ArmaghanSarvar** [UBC-MDS/VanArt#43]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, excellent work! Below we list some specific feedback you can use to improve your project.

- Submission instructions: mechanics: 4/4

- Developing your Shiny App: mechanics: 13/15, quality: 5/5, viz: 15/15, accuracy: 7/7
•	The app's reactivity is working as expected 
•	There is one branch by each team member 
•	Labels in the Input widgets are not missing. 
•	Plot axis are not missing.
•	The elements of the app are organized. 
•	There is an app title.
•	The plots, labels, and titles are easy to read **-2**
o	Art type panel, the second art type picked, the number cannot be seen.
•	The link to the dashboard is clearly visible near the top of your README. 
•	The app is correctly deployed. 

- Reflection: reasoning: 2/6
•	There is reflection-milestone2.md file and it is more than 500 words  **-4**
       o	The total text is 377, required is around 500 words. 
       o	Additional feedback: The title can be a bigger and bolder font without emojis. 
       o	 The bars for adjusting data can be a bit tidier if they were stacked on the left.
•	reflection-milestone2.md is included in the docs folder 
•	Reading reflection-milestone2.md and comparing it with the milestone1 sketch, it is possible to understand what has changed and why 

- Improve the README: reasoning: 2/6
•	README.md: There is a project motivation section/explanation. **-2**
•	README.md: There is a high-level users instructions and gif showing the app usage 
•	README.md: It is prepared for potential collaborators. There is information included on how to install the app and run it locally. **-2**

**Comment by robindhillon1** [comment]
Hi @ArmaghanSarvar, we have a bunch of regrade requests please:
1. Reflection: our reflection is ~400 words and the instructions are to have less than 500 words.
2. "README.md: There is a project motivation section/explanation." Yes, we have a project motivation section/explanation. It is called `The problem` and `The solution` under `Introduction` in the README. Please see here: https://github.com/UBC-MDS/VanArt#introduction
3. "README.md: It is prepared for potential collaborators. There is information included on how to install the app and run it locally" We also have in the readme. Please see here: https://github.com/UBC-MDS/VanArt#contributing

We appreciate your feedback on our work, and we believe that with these changes, our project will be even better. However, we kindly request that we not lose points for details that were taken care of already.

Thank you for your understanding and support.
