### ISSUE TITLE
[MS4] Improvements

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/VanArt#44]
**General Improvements**
- Make description pop-up more readable 
- Progress bar (?) 
- Add a download button for graphs 
- Add a download button for addresses of art pieces (?) 
- Add a download button for a report @Hongjian-Sam-Li 
- Make drop-down options in alphabetical order (?) 
- Add a choropleth map + radio button to switch between original and choropleth 
- Put notification info + recreation in README.md (?) 
- Improve theme of the app (colour and fonts) or include a dark mode radio button @LisaSeq 

**TA Feedback ([link](https://github.com/UBC-MDS/VanArt/issues/43))**
- Change colour scheme so art-type values are visible @LisaSeq 
   - "Art type panel, the second art type picked, the number cannot be seen."
- Make title bigger, bolder, no emojis  @shlrley 
   - "The title can be a bigger and bolder font without emojis."
- Move bars to the left (?) 
   - "The bars for adjusting data can be a bit tidier if they were stacked on the left."
- Add more information for potential collaborators 
   - "README.md: It is prepared for potential collaborators. There is information included on how to install the app and run it locally."

**Peer Review Feedback ([link](https://github.ubc.ca/fdandrea/532-peer-review/issues/21))**
- Change the x-axis for year to integer/categorical instead of continuous @Hongjian-Sam-Li 
   - "For example the combination Art Type: Memorial or Monument + Neighborhood: Mount Pleasant has values in the Year Installed plot of 2009.75, 2010.00."
   - "If you add something like this to your plot, it seems to fix the problem: `scale_x_continuous(breaks = seq(1950, 2020, 10))`"
- Improve map if a combination of no art pieces exist @robindhillon1 
   - "It would probably be better to show empty map or show a message which saying something like: 'No Art for this period with the selected criteria.'"
   - Notification pop-up 
   - Keep map on Vancouver, but empty  
- Update README.md and take out filtering by artists

**Comment by robindhillon1** [comment]
Put notification info + recreation in Readme.
