### ISSUE TITLE
[MS4] Lisa's Tasks

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/VanArt#46]
**Fixes**

- [x] Change the colour scheme of the tree graph so that numbers are visible against square 

**Improvements**

- [x] Improve theme of the app (colour and fonts) or include a dark mode (that can be switched to using a radio button)

**Testing**

- [x] Include at least 3 tests created with the package shinytests2 

**Reflection**

- [x] Document what you have implemented in your dashboard so far and explain what is not yet implemented (in `docs/reflection-milestone4.md`)

**Comment by LisaSeq** [comment]
Completed all tasks as per PR #68
