### ISSUE TITLE
[MS4] Robin's Tasks

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/VanArt#47]
**Fixes**

- [x] Update README.md and take out filtering by artists
- [x] Add more information for potential collaborators

**Improvements** 

- [x] Improve map if a combination of no art pieces exist 

**Reflection**

- [x] Document what you have implemented in your dashboard so far and explain what is not yet implemented (in `docs/reflection-milestone4.md`)

**Comment by robindhillon1** [comment]
Improvements done:
- Accounted for cases when no art exists: displays all the public art in Vancouver now and also shows a notification to notify the user that no art exists for that combination of user input. The notification stays for 30 seconds and the duration can be increased/decreased, and the user can manually close it.

**Comment by robindhillon1** [comment]
done and done

**Comment by robindhillon1** [comment]
Modification: Improved the main leaflet map when no artworks exist depending on user input. Now it shows all the art in Vancouver in such scenarios and a notification is also displayed to the user. 
Source: Peer review milestone 3 (https://github.ubc.ca/fdandrea/532-peer-review/issues/21#issuecomment-23020)
Team member: Robin Dhillon
Commit/s: https://github.com/UBC-MDS/VanArt/commit/4aa42b4ecb2241d443a7599636d3b31e3e7b5ce3, 

Modification: Added three different toggleable map types such as a `Basemap`, `Neighbourhood` map, and `Satellite view` map. This improvement increases ease-of-use for the user. 
Source: Initial improvements thought by our group here (https://github.com/UBC-MDS/VanArt/issues/44#issue-1622259209)
Team member: Robin Dhillon
Commit/s: https://github.com/UBC-MDS/VanArt/commit/770e0c6e32c61997ec8ee7bf5fc120da45f39c76, https://github.com/UBC-MDS/VanArt/commit/3efa70b0841ad8de18908c3698f9ec6434717436

Modification: Updated readme to include complete installation instructions as well as a more detailed contributing section as per TA feedback. Also added badges of CI/CD status in README.
Source: TA feedback (https://github.com/UBC-MDS/VanArt/issues/43#issue-1620548733 + Slack)
Team member: Robin Dhillon
Commit/s: https://github.com/UBC-MDS/VanArt/commit/677799b17cc217cbad4bd7448d001ad5cb46b19c, https://github.com/UBC-MDS/VanArt/commit/88bcfff23e3785a6decdfa2354932300d53f5026, https://github.com/UBC-MDS/VanArt/commit/34d414b37836453b5f579a924be77dec28d6319d

Modification: Added spinners 
Source: Milestone 4 (https://pages.github.ubc.ca/MDS-2022-23/DSCI_532_viz-2_students/materials/assignments/milestone4.html)
Team member: Robin Dhillon
Commit/s: https://github.com/UBC-MDS/VanArt/commit/1d4eb1f38e6c90910b016ff7fd4221ee209125ab
