### ISSUE TITLE
[MS4] Sam's Tasks 

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/VanArt#48]
**Fixes**

- [x] Change the x-axis for year to integer/categorical instead of continuous 

**Improvements**

- [x] Add a download button for a parametrized report 

**Reflection**

- [x] Document what you have implemented in your dashboard so far and explain what is not yet implemented (in `docs/reflection-milestone4.md`)

**Other** 

- [x] Raise issues with the Milestone 2 feedback

**Comment by Hongjian-Sam-Li** [comment]
Modification: Add a download button to allow users to download .tsv file of the filtered data they selected on our dashboard
Source: Milestone 4 improvement example([paste the link to the comment](https://pages.github.ubc.ca/MDS-2022-23/DSCI_532_viz-2_students/materials/assignments/milestone4.html#))
Team member: Hongjian(Sam) Li
Commit/s: https://github.com/UBC-MDS/VanArt/commit/805e160a8af0b1ab7a7e2a69f5d27017a24fe3ca

**Comment by Hongjian-Sam-Li** [comment]
Modification: Fixed the scale problem of the density plot's x-axis, converted the continuous date variable to discrete
Source: Milestone 3 peer review(https://github.ubc.ca/fdandrea/532-peer-review/issues/21#issuecomment-23020)
Team member: Hongjian(Sam) Li
Commit/s: https://github.com/UBC-MDS/VanArt/commit/1a9f14b7c3bc2066d4cebc264f6f42f0d35d17b8
